name: security
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "23 4 * * 1"
jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: 'go.mod'
      - name: Download modules
        run: go mod download
      - name: Verify modules
        run: go mod verify
      - name: Run govulncheck
        run: go tool govulncheck ./...
